### ISSUE TITLE
[Feature request] Is itr possible for multi-user support?

### ISSUE THREAD

**Issue by Kihara777** [KieronQuinn/DarQ#65] opened 2022-07-30 04:20 UTC
I'm using "Island"(com.oaisisfeng.island) which use Android for Work mechanism to create an isolated space (normally is user 10, might be higher if you destroy island space an create a new one).
However the DarQ is not able to connect to shizuku service in island space, and the main user's DarQ app can't select any island space app either. I have to use force dark overwrite to let the darkmode work for island space apps, and since we don't have any blacklist mode, it certainly cause some readability issue, like the Gboard.

So, is it possible to add multi-user app support for DarQ?

**Comment by KieronQuinn** [comment] 2022-08-04 00:17
Duplicate of #40

**Closed by KieronQuinn** 2022-08-04 00:17 UTC
