### ISSUE TITLE
[Feature Request] Support Work Profile Apps

### ISSUE THREAD

**Issue by Venderbad** [KieronQuinn/DarQ#77] opened 2023-02-05 08:30 UTC
The apps in work profile is not selectable in DarQ if DarQ is installed in the main user profile. Therefore, I thought the only way to dark the apps in the work profile is to install another DarQ in the work profile. But after installation and granting permission in Sui, I launched the work profile DarQ, and it says Shizuku is not installed, and I don't have root privilege. Problem is I use Sui instead of Shizuku for DarQ in main user, and it worked perfectly, yet my DarQ in work profile does not.

Hope the great devs can add support to affect work profile apps, and DarQ would be even more perfect.

**Comment by KieronQuinn** [comment] 2023-02-17 23:35
This is a duplicate of #40 since work profile is actually just a second user.

**Closed by KieronQuinn** 2023-02-17 23:35 UTC
